### PR TITLE
updated Money.parse/1 to work with decimal ~> 1.2 and ~> 2.0

### LINKED ISSUE #213: Unable to parse string
I am experiencing the same issue as #202 . 

My current setup is the following:
Nixos: 23.11
Dependencies:
  appsignal 2.7.3
  appsignal_phoenix 2.3.2
  appsignal_plug 2.0.13
  artificery 0.4.3
  bamboo 2.1.0
  bamboo_phoenix 1.0.0
  bamboo_smtp 4.0.1
  bcrypt_elixir 2.3.1
  browser 0.4.4
  bunt 0.2.1
  burnex 3.1.0
  castore 1.0.4
  cc_precompiler 0.1.9
  certifi 2.12.0
  cldr_utils 2.24.2
  comeonin 5.4.0
  cowboy 2.10.0
  cowboy_telemetry 0.3.1
  cowlib 2.12.1
  credo 1.7.1
  dart_sass 0.7.0
  db_connection 2.6.0
  decimal 1.9.0
  decorator 1.4.0
  distillery 2.1.1
  dns 2.2.0
  earmark 1.4.46
  ecto 3.10.3
  ecto_commons 0.3.3
  ecto_sql 3.10.2
  edeliver 1.9.2
  elixir_make 0.7.7
  esbuild 0.8.1
  ex_cldr 2.37.5
  ex_cldr_territories 2.2.2
  ex_phone_number 0.4.3
  exexif 0.0.5
  expo 0.4.1
  file_system 0.2.10
  finch 0.16.0
  fuzzy_compare 1.0.0
  gen_smtp 1.1.1
  gettext 0.23.1
  glob_ex 0.1.6
  hackney 1.20.1
  hpax 0.1.2
  httpoison 1.8.2
  hut 1.3.0
  idna 6.1.1
  image 0.39.3
  inflex 2.1.0
  jason 1.4.1
  luhn 0.3.3
  metrics 1.0.1
  mimerl 1.2.0
  mint 1.5.1
  miss 0.1.5
  mneme 0.4.3
  mogrify 0.9.3
  mollie 0.7.2
  money 1.12.3
  msgpax 2.4.0
  nimble_options 1.0.2
  nimble_pool 1.0.0
  owl 0.7.0
  parse_trans 3.4.1
  phoenix 1.7.10
  phoenix_ecto 4.4.3
  phoenix_html 3.3.3
  phoenix_live_reload 1.4.1
  phoenix_pubsub 2.1.3
  phoenix_template 1.0.3
  phoenix_view 2.0.3
  plug 1.15.2
  plug_cowboy 2.6.1
  plug_crypto 2.0.0
  postgrex 0.17.3
  ranch 1.8.0
  rewrite 0.7.1
  socket 0.3.13
  sourceror 0.12.3
  ssl_verify_fun 1.1.7
  surface 0.11.1
  surface_font_awesome 0.4.2
  surface_markdown 0.6.1
  surface_utils 0.1.0
  sweet_xml 0.7.4
  telemetry 0.4.3
  telemetry_metrics 0.6.1
  telemetry_poller 0.5.1
  tzdata 1.1.1
  unicode_util_compat 0.7.0
  vix 0.26.0
  websock 0.5.3
  websock_adapter 0.5.5

### PR DESCRIPTION
**Pull request by gabrielperales**
Closes #213 

I had to use [Blend](https://github.com/mimiquate/blend) to test Money with decimal 1.2 and 2.0. 

Now, there is a `blend.exs` file with the differents supported versions of decimal. You can install and run different dependencies versions using the `BLEND` environment variable as it is described [here](https://github.com/mimiquate/blend?tab=readme-ov-file#3-enjoy). 

I have also updated the GitHub action to run the tests with both versions :).

### CODE REVIEW

**Review by Nitrino — APPROVED** [review]
Thanks for the fix.
I don't like that this will make our tests 2x slower, but we'll leave your option for now

**Comment by gabrielperales** [comment]
> Thanks for the fix. I don't like that this will make our tests 2x slower, but we'll leave your option for now

We can run only the `Money.parse` tests for decimal 1.2.

**Comment by gabrielperales** [comment]
> Thanks for the fix. I don't like that this will make our tests 2x slower, but we'll leave your option for now

I have updated the CI to run only the test wich uses Decimal with `decimal ~> 1.2`

**Comment by Nitrino** [comment]
@gabrielperales Thanks for all your contributions ❤️

**Comment by gabrielperales** [comment]
@Nitrino You are welcome! I'm an Elixir newbie and contributing to open-source projects always helps to catch up on good practices 💪 . On the other hand, the new feature for configuring currency display options is going to be helpful for our projects :)

**Pull request merged**
