### PR TITLE
Fixes #184 Correct Currency Symbols

### LINKED ISSUE #184: Incorrect currency Symbols
The symbols for Canadian and Singaporean dollar are incorrect.

Should be `Can$` and `S$` respectively.

[Language Navigator – Canadian dollar (symbol) (Linguistic](https://www.noslangues-ourlanguages.gc.ca/en/writing-tips-plus/canadian-dollar-symbol) 
[Canadian dollar](https://en.wikipedia.org/wiki/Canadian_dollar) 
[Singapore dollar](https://en.wikipedia.org/wiki/Singapore_dollar)

### PR DESCRIPTION
**Pull request by kevinkirkup**
Fix Canadian and Singaporean Dollar symbols.

### CODE REVIEW

**Comment by kevinkirkup** [comment]
How do I get this in?

**Comment by Nitrino** [comment]
Thanks :heart:

**Comment by kevinkirkup** [comment]
np. Any chance we can get a `1.10.1` patch release to include this?

**Comment by darrenklein** [comment]
Would `1.11.0` be the release, since it would also include the new feature from https://github.com/elixirmoney/money/pull/183?

**Comment by Nitrino** [comment]
@kevinkirkup @darrenklein  v1.11.0 released 
https://hex.pm/packages/money/1.11.0

**Comment by darrenklein** [comment]
My pleasure, really honored to have had the opportunity to contribute to this project. Thank you for all of your hard work.

**Pull request merged**
