### PR TITLE
Improve Money.to_decimal to respect decimal places

### PR DESCRIPTION
**Pull request by michel-boaventura**
Before this PR:

```Elixir
Money.new(100, "USD") |> Money.to_decimal() |> Decimal.to_string() == "1.0"
```

After this PR:

```Elixir
Money.new(100, "USD") |> Money.to_decimal() |> Decimal.to_string() == "1.00"
```

Which is particularly useful to generate json with the correct number of decimal places.

Also fix some credo/dialyzer warnings.

### CODE REVIEW

**Comment by michel-boaventura** [comment]
The CI error seems to be caused by an older Elixir version:

```
warning: the dependency :credo requires Elixir ">= 1.7.0" but you are running on v1.6.6
```

Should I downgrade credo o change Travis to stop testing with v1.6.6?

**Comment by Nitrino** [comment]
Hi @michel-boaventura, 
Thank you for your contribution.
I think it's better to downgrade the credo version for now.

**Comment by michel-boaventura** [comment]
Fixed, thanks!

**Comment by Nitrino** [comment]
@michel-boaventura Thanks 👍

**Pull request merged**
